In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
train_df = pd.read_csv('../input/hack-the-vibe/dataset/train.csv', low_memory=False)
test_df = pd.read_csv('../input/hack-the-vibe/dataset/test.csv', low_memory=False)

In [3]:
train_df.head()

,id,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,...,var_5470,var_5471,var_5472,var_5473,var_5474,var_5475,var_5476,var_5477,var_5478,target
0,id_1,0.015625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.355422,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,id_2,0.187500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.150602,...,0.0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0
2,id_3,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,NaN,NaN,0.008333,NaN,NaN,0.0,NaN,NaN,0.0,0
3,id_4,0.156250,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.018072,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,id_5,0.046875,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.096386,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [4]:
train_df.columns

Index(['id', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7',
       'var_8', 'var_9',
       ...
       'var_5470', 'var_5471', 'var_5472', 'var_5473', 'var_5474', 'var_5475',
       'var_5476', 'var_5477', 'var_5478', 'target'],
      dtype='object', length=5480)

In [5]:
train_df.shape

(25000, 5480)

In [6]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Columns: 5480 entries, id to target
dtypes: float64(5478), int64(1), object(1)
memory usage: 1.0+ GB

In [7]:
train_df.describe()

/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py:4009: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,var_10,...,var_5470,var_5471,var_5472,var_5473,var_5474,var_5475,var_5476,var_5477,var_5478,target
count,22876.000000,22876.000000,22876.000000,22876.000000,22876.000000,22876.0,22876.000000,22876.000000,14250.000000,15220.000000,...,2183.000000,12.000000,6487.000000,656.000000,1104.000000,1026.000000,789.000000,7.000000,2570.000000,25000.000000
mean,0.047580,0.000962,0.000393,0.000437,0.000262,0.0,0.003251,0.004022,0.072058,0.109653,...,0.020516,0.285714,0.010233,0.021596,0.014560,0.026578,0.048247,0.178571,0.012042,0.146840
std,0.073311,0.017310,0.013400,0.020904,0.013221,0.0,0.028457,0.035609,0.102805,0.012076,...,0.047998,0.355189,0.025074,0.062241,0.041933,0.062204,0.099965,0.374007,0.032418,0.353953
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.012048,0.106633,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.015625,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.018072,0.106633,...,0.000000,0.142857,0.004167,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.062500,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.096386,0.107524,...,0.017857,0.464286,0.012500,0.033333,0.018519,0.038462,0.066667,0.125000,0.008621,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
class_distribution = pd.value_counts(train_df['target'], normalize=True)
print(class_distribution)

0    0.85316
1    0.14684
Name: target, dtype: float64

In [9]:
train_df.shape

(25000, 5480)

In [10]:
train_df.isnull().sum()/len(train_df)

id          0.00000
var_1       0.08496
var_2       0.08496
var_3       0.08496
var_4       0.08496
             ...
var_5475    0.95896
var_5476    0.96844
var_5477    0.99972
var_5478    0.89720
target      0.00000
Length: 5480, dtype: float64

In [11]:
potential_zeros = []
for col in train_df.columns:
    if max(train_df[col])==min(train_df[col]): 
        potential_zeros.append(col)

train_df.drop(columns=potential_zeros, inplace=True)
test_df.drop(columns=potential_zeros, inplace=True)

In [12]:
train_df.describe()

/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py:4009: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,var_1,var_2,var_3,var_4,var_5,var_7,var_8,var_9,var_10,var_11,...,var_5470,var_5471,var_5472,var_5473,var_5474,var_5475,var_5476,var_5477,var_5478,target
count,22876.000000,22876.000000,22876.000000,22876.000000,22876.000000,22876.000000,22876.000000,14250.000000,15220.000000,1716.000000,...,2183.000000,12.000000,6487.000000,656.000000,1104.000000,1026.000000,789.000000,7.000000,2570.000000,25000.000000
mean,0.047580,0.000962,0.000393,0.000437,0.000262,0.003251,0.004022,0.072058,0.109653,0.106531,...,0.020516,0.285714,0.010233,0.021596,0.014560,0.026578,0.048247,0.178571,0.012042,0.146840
std,0.073311,0.017310,0.013400,0.020904,0.013221,0.028457,0.035609,0.102805,0.012076,0.094521,...,0.047998,0.355189,0.025074,0.062241,0.041933,0.062204,0.099965,0.374007,0.032418,0.353953
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.012048,0.106633,0.048945,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.015625,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018072,0.106633,0.080466,...,0.000000,0.142857,0.004167,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.062500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.096386,0.107524,0.134115,...,0.017857,0.464286,0.012500,0.033333,0.018519,0.038462,0.066667,0.125000,0.008621,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [13]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Columns: 3417 entries, id to target
dtypes: float64(3415), int64(1), object(1)
memory usage: 651.7+ MB

In [14]:
train_df.set_index('id', inplace=True)
test_df.set_index('id', inplace=True)

In [15]:
train_df.head()

,var_1,var_2,var_3,var_4,var_5,var_7,var_8,var_9,var_10,var_11,...,var_5470,var_5471,var_5472,var_5473,var_5474,var_5475,var_5476,var_5477,var_5478,target
id,,,,,,,,,,,,,,,,,,,,,
id_1,0.015625,0.0,0.0,0.0,0.0,0.0,0.0,0.355422,0.106633,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
id_2,0.187500,0.0,0.0,0.0,0.0,0.0,0.0,0.150602,0.106633,NaN,...,0.0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0
id_3,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,0.008333,NaN,NaN,0.0,NaN,NaN,0.0,0
id_4,0.156250,0.0,0.0,0.0,0.0,0.0,0.0,0.018072,0.106633,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
id_5,0.046875,0.0,0.0,0.0,0.0,0.0,0.0,0.096386,0.106633,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [16]:
more_than_0_8_null = train_df.isnull().sum()/len(train_df)
columns_to_drop = more_than_0_8_null[more_than_0_8_null>=0.8]
train_df[columns_to_drop.index].describe()

,var_11,var_15,var_19,var_20,var_23,var_24,var_27,var_31,var_35,var_39,...,var_5468,var_5469,var_5470,var_5471,var_5473,var_5474,var_5475,var_5476,var_5477,var_5478
count,1716.000000,1716.000000,1585.000000,4949.000000,1585.000000,4949.00000,1716.000000,1716.000000,1703.000000,1703.000000,...,3249.000000,3125.000000,2183.000000,12.000000,656.000000,1104.000000,1026.000000,789.000000,7.000000,2570.000000
mean,0.106531,0.115491,0.001851,0.002248,0.001851,0.00233,0.003106,0.003077,0.107469,0.116445,...,0.012645,0.027284,0.020516,0.285714,0.021596,0.014560,0.026578,0.048247,0.178571,0.012042
std,0.094521,0.100444,0.038160,0.033769,0.038160,0.03447,0.047445,0.047446,0.094629,0.100424,...,0.031637,0.058171,0.047998,0.355189,0.062241,0.041933,0.062204,0.099965,0.374007,0.032418
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.048945,0.053451,0.000000,0.000000,0.000000,0.00000,0.000321,0.000321,0.049435,0.055111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.080466,0.088740,0.000000,0.000000,0.000000,0.00000,0.000579,0.000576,0.081484,0.089562,...,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.134115,0.145646,0.000000,0.000000,0.000000,0.00000,0.001030,0.000965,0.135119,0.146380,...,0.010638,0.026316,0.017857,0.464286,0.033333,0.018519,0.038462,0.066667,0.125000,0.008621
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [17]:
train_df.drop(columns=columns_to_drop.index, inplace=True)
test_df.drop(columns=columns_to_drop.index, inplace=True)

In [18]:
train_df.describe()

/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py:4009: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,var_1,var_2,var_3,var_4,var_5,var_7,var_8,var_9,var_10,var_12,...,var_5457,var_5458,var_5460,var_5461,var_5462,var_5463,var_5464,var_5466,var_5472,target
count,22876.000000,22876.000000,22876.000000,22876.000000,22876.000000,22876.000000,22876.000000,14250.000000,15220.000000,5361.000000,...,21928.000000,13654.000000,24792.000000,16195.000000,18417.000000,17191.000000,10891.000000,22602.000000,6487.000000,25000.000000
mean,0.047580,0.000962,0.000393,0.000437,0.000262,0.003251,0.004022,0.072058,0.109653,0.045097,...,0.033637,0.049357,0.044753,0.028822,0.020902,0.029584,0.034038,0.025610,0.010233,0.146840
std,0.073311,0.017310,0.013400,0.020904,0.013221,0.028457,0.035609,0.102805,0.012076,0.046638,...,0.045828,0.064017,0.052075,0.052249,0.036365,0.050108,0.054235,0.038125,0.025074,0.353953
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.012048,0.106633,0.020052,...,0.006135,0.008547,0.013986,0.000000,0.000000,0.000000,0.000000,0.005249,0.000000,0.000000
50%,0.015625,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018072,0.106633,0.033845,...,0.018405,0.025641,0.027972,0.013158,0.006711,0.009804,0.010526,0.013123,0.004167,0.000000
75%,0.062500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.096386,0.107524,0.055642,...,0.042945,0.068376,0.055944,0.039474,0.026846,0.039216,0.042105,0.031496,0.012500,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [19]:
train_df.isnull().sum().sum()

12746269

In [20]:
avg = train_df.mode().iloc[0] # .mean()

In [21]:
train_df.fillna(avg, inplace=True)
test_df.fillna(avg, inplace=True)

In [22]:
print(np.isinf(train_df).sum().sum())
print(np.isinf(test_df).sum().sum())

12600
2553

In [23]:
(np.isinf(test_df).sum()).sort_values()

var_1          0
var_3739       0
var_3738       0
var_3737       0
var_3736       0
            ...
var_1298       0
var_1297       0
var_1339       0
var_5472       0
var_5213    2553
Length: 1554, dtype: int64

In [24]:
train_df.drop('var_5213', axis=1, inplace=True)
test_df.drop('var_5213', axis=1, inplace=True)

In [25]:
test_df

,var_1,var_2,var_3,var_4,var_5,var_7,var_8,var_9,var_10,var_12,...,var_5456,var_5457,var_5458,var_5460,var_5461,var_5462,var_5463,var_5464,var_5466,var_5472
id,,,,,,,,,,,,,,,,,,,,,
id_1,0.015625,0.00,0.0,0.0,0.0,0.000,0.00,0.018072,0.128426,0.006359,...,0.059524,0.036810,0.068376,0.079254,0.052632,0.046980,0.049020,0.084211,0.070866,0.012500
id_2,0.015625,0.00,0.0,0.0,0.0,0.000,0.00,0.018072,0.111644,0.006359,...,0.041667,0.055215,0.000000,0.069930,0.105263,0.026846,0.029412,0.000000,0.044619,0.000000
id_3,0.015625,0.00,0.0,0.0,0.0,0.000,0.00,0.012048,0.106633,0.006359,...,0.017857,0.049080,0.000000,0.037296,0.000000,0.000000,0.029412,0.000000,0.010499,0.000000
id_4,0.000000,0.00,0.0,0.0,0.0,0.000,0.00,0.012048,0.106633,0.006359,...,0.029762,0.006135,0.000000,0.020979,0.026316,0.020134,0.000000,0.000000,0.015748,0.000000
id_5,0.046875,0.00,0.0,0.0,0.0,0.000,0.00,0.012048,0.106633,0.006359,...,0.011905,0.006135,0.000000,0.011655,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
id_4996,0.015625,0.25,0.0,0.0,0.0,0.000,0.25,0.024096,0.122799,0.006359,...,0.000000,0.006135,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
id_4997,0.093750,0.00,0.0,0.0,0.0,0.000,0.00,0.108434,0.106633,0.006359,...,0.029762,0.000000,0.000000,0.025641,0.013158,0.013423,0.000000,0.000000,0.013123,0.000000
id_4998,0.000000,0.00,0.0,0.0,0.0,0.125,0.00,0.367470,0.110760,0.006359,...,0.005952,0.018405,0.017094,0.023310,0.000000,0.000000,0.000000,0.000000,0.002625,0.000000
id_4999,0.000000,0.00,0.0,0.0,0.0,0.000,0.00,0.012048,0.106633,0.006359,...,0.041667,0.024540,0.068376,0.062937,0.052632,0.013423,0.029412,0.021053,0.036745,0.004167
id_5000,0.000000,0.00,0.0,0.0,0.0,0.000,0.00,0.012048,0.106633,0.006359,...,0.023810,0.061350,0.000000,0.041958,0.000000,0.000000,0.039216,0.000000,0.015748,0.000000

In [26]:
# train_df.replace([np.inf, -np.inf], np.finfo(np.float32).max, inplace=True)
# test_df.replace([np.inf, -np.inf], np.finfo(np.float32).max, inplace=True)

In [27]:
train_df.to_csv('cleaned_train_data.csv')
test_df.to_csv('cleaned_test_data.csv')

In [28]:
df = train_df

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('target', axis=1), df['target'], test_size=0.3, random_state=42)

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
# Logistic Regression
clf = LogisticRegression(solver='saga')

# Training model on the training set
clf.fit(X_train, y_train)

# Evaluating the performance of model on the testing set
# score = clf.score(X_test, y_test)
y_pred = clf.predict(X_test)
y_prob = clf.predict_proba(X_test)[:,1]

from sklearn.metrics import roc_auc_score
print('AUC-ROC score:', roc_auc_score(y_test, y_prob))

AUC-ROC score: 0.684068953650477

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
# Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Training model on the training set
clf.fit(X_train, y_train)

# Evaluating the performance of model on the testing set
# score = clf.score(X_test, y_test)
y_pred = clf.predict(X_test)
y_prob = clf.predict_proba(X_test)[:,1]

from sklearn.metrics import roc_auc_score
print('AUC-ROC score:', roc_auc_score(y_test, y_prob))

AUC-ROC score: 0.6973792275196562

In [35]:
import xgboost as xgb

In [36]:
# XGBoost Classifier
clf = xgb.XGBClassifier(n_estimators=100, max_depth=5, learning_rate=0.1, subsample=0.8, colsample_bytree=0.8, random_state=42)

# Training model on the training set
clf.fit(X_train, y_train)

# Evaluating the performance of model on the testing set
# score = clf.score(X_test, y_test)
y_pred = clf.predict(X_test)
y_prob = clf.predict_proba(X_test)[:,1]

from sklearn.metrics import roc_auc_score
print('AUC-ROC score:', roc_auc_score(y_test, y_prob))

AUC-ROC score: 0.7171547664614726

In [37]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
import xgboost as xgb

# Split the data into training and test sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the base models (XGBoost and logistic regression)
xgb_model = xgb.XGBClassifier(n_estimators=100, max_depth=5, learning_rate=0.1, subsample=0.8, colsample_bytree=0.8, random_state=42)
lr_model = LogisticRegression(solver='saga',random_state=42)

# Define the meta-model (logistic regression)
meta_model = LogisticRegression(solver='saga',random_state=42)

# Use KFold cross-validation to generate meta-features
kf = KFold(n_splits=5)
X_meta = np.zeros((X_train.shape[0], 2))

for train_idx, val_idx in kf.split(X_train):
    xgb_model.fit(X_train.iloc[train_idx], y_train.iloc[train_idx])
    lr_model.fit(X_train.iloc[train_idx], y_train.iloc[train_idx])
    X_meta[val_idx, 0] = xgb_model.predict_proba(X_train.iloc[val_idx])[:,1]
    X_meta[val_idx, 1] = lr_model.predict_proba(X_train.iloc[val_idx])[:,1]

# Train the meta-model on the meta-features
meta_model.fit(X_meta, y_train)

# Generate meta-features for the test data
X_meta_test = np.zeros((X_test.shape[0], 2))
X_meta_test[:,0] = xgb_model.predict_proba(X_test)[:,1]
X_meta_test[:,1] = lr_model.predict_proba(X_test)[:,1]

# Use the meta-model to make final predictions on the test data
y_pred = meta_model.predict(X_meta_test)

# Calculate the ROC AUC score on the test data
roc_auc = roc_auc_score(y_test, y_pred)
print("ROC AUC score:", roc_auc)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,

ROC AUC score: 0.5328765920687148

In [38]:
from sklearn.model_selection import GridSearchCV

# define the parameter grid to search over
param_grid = {
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1],
    'n_estimators': [50, 100, 200],
    'gamma': [0, 0.1, 0.5],
}

# create the XGBoost model
xgb_model = xgb.XGBClassifier()

# create the GridSearchCV object
grid_search = GridSearchCV(xgb_model, param_grid, cv=5, scoring='roc_auc')

# fit the GridSearchCV object to the training data
# grid_search.fit(X_train, y_train)
grid_search.fit(X_train, y_train, verbose=4)

# print the best set of hyperparameters and the corresponding ROC AUC score
print("Best hyperparameters: ", grid_search.best_params_)
print("Best ROC AUC score: ", grid_search.best_score_)

Best hyperparameters:  {'gamma': 0.5, 'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}
Best ROC AUC score:  0.7201504967222767